package com.core.rule.dao;

import com.core.rule.bean.dataObj.DraftDo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DraftDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int insert(DraftDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    //DraftDoWithBLOBs selectByPrimaryKey(Long id);
    //TODO:是否需要创建该对象。

    DraftDo selectByDraftNo(String draftNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    List<DraftDo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int updateByPrimaryKey(DraftDo record);
}