package com.core.rule.dao;

import com.core.rule.bean.dataObj.CompositDTO;
import com.core.rule.bean.dataObj.DraftDo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DraftDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int deleteByPrimaryKey(Long id);
    int deleteByPrimaryKey2(String draftno);
    int deleteByPrimaryKey3(DraftDo draftno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int insert(DraftDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    //DraftDoWithBLOBs selectByPrimaryKey(Long id);
    //TODO:是否需要创建该对象。

    DraftDo selectByDraftNo(String draftNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    List<DraftDo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft
     *
     * @mbg.generated Fri Nov 22 09:03:32 CST 2019
     */
    int updateByPrimaryKey(DraftDo record);
    int updateByPrimaryKey2(DraftDo record);
    int insertBatch(List records);

    //注意这里的@Param是myabtis注解
    @Select("select * from draft where ${column} = #{value}")
    List<DraftDo> selectByDraftNo1(@Param("column") String column , @Param("value") String value);

    //定义一个复合连表操作 定义对象返回resultmap　　
// 定义者需要判断是否返回可能list    CompositDTO selectComposit();
    List selectComposit();

    List selectBySearchBean(DraftDo draftDo2);
    List selectByin(List l);
    List selectLike(DraftDo draftDo);

    DraftDo  selectByPrimaryKey(long id);
}