/*
package com.core.rule.dao;

import com.core.rule.bean.dataObj.PropertyDo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PropertyDoMapper {
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Thu Nov 21 16:40:05 CST 2019
     *//*

    int deleteByPrimaryKey(Long id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Thu Nov 21 16:40:05 CST 2019
     *//*

    int insert(PropertyDo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Thu Nov 21 16:40:05 CST 2019
     *//*

    PropertyDo selectByPrimaryKey(Long id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Thu Nov 21 16:40:05 CST 2019
     *//*

    List<PropertyDo> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Thu Nov 21 16:40:05 CST 2019
     *//*

    int updateByPrimaryKey(PropertyDo record);
}*/
