/*
package com.busi.seckill.dao;

import com.secKill.dataObj.UserDo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserDoMapper {
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 13 19:02:20 CST 2019
     *//*

    int deleteByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 13 19:02:20 CST 2019
     *//*

    int insert(UserDo record);

    int insertSelective(UserDo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 13 19:02:20 CST 2019
     *//*

    UserDo selectByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 13 19:02:20 CST 2019
     *//*

    List<UserDo> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 13 19:02:20 CST 2019
     *//*

    int updateByPrimaryKey(UserDo record);
}*/
