package com.register.dao;

import com.register.bean.dataObj.RgctStudentHist;
import java.util.List;

public interface RgctStudentHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_hist
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int deleteByPrimaryKey(Long histId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_hist
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int insert(RgctStudentHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_hist
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    RgctStudentHist selectByPrimaryKey(Long histId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_hist
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    List<RgctStudentHist> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_hist
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int updateByPrimaryKey(RgctStudentHist record);
}