package com.register.dao;

import com.register.bean.dataObj.RgctStudentInfo;
import java.util.List;

public interface RgctStudentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_info
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_info
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int insert(RgctStudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_info
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    RgctStudentInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_info
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    List<RgctStudentInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_student_info
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int updateByPrimaryKey(RgctStudentInfo record);
}