package com.register.dao;

import com.register.bean.dataObj.RgctMethod;
import java.util.List;

public interface RgctMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_method
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_method
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int insert(RgctMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_method
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    RgctMethod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_method
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    List<RgctMethod> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rgct_method
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int updateByPrimaryKey(RgctMethod record);
}