package com.register.dao;

import com.register.bean.dataObj.StatusDo;
import java.util.List;

public interface StatusDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    int insert(StatusDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    StatusDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    List<StatusDo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    int updateByPrimaryKey(StatusDo record);
}