package com.register.dao;

import com.register.bean.dataObj.Status;
import java.util.List;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    Status selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    List<Status> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int updateByPrimaryKey(Status record);
}