package com.register.dao;

import com.register.bean.dataObj.StatusDictionary;
import java.util.List;

public interface StatusDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statusdictionary
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statusdictionary
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int insert(StatusDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statusdictionary
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    StatusDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statusdictionary
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    List<StatusDictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statusdictionary
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    int updateByPrimaryKey(StatusDictionary record);
}