package com.register.bean.dataObj;

public class RgctStudentHist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Long histId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.begin_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.end_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.operate
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String operate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.last_hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Long lastHistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.age
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.class_name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.current_state
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Integer currentState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.is_lock
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Integer isLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.lock_scence
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String lockScence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_student_hist.nested_deep
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Integer nestedDeep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.hist_id
     *
     * @return the value of rgct_student_hist.hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Long getHistId() {
        return histId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.hist_id
     *
     * @param histId the value for rgct_student_hist.hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setHistId(Long histId) {
        this.histId = histId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.begin_date
     *
     * @return the value of rgct_student_hist.begin_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.begin_date
     *
     * @param beginDate the value for rgct_student_hist.begin_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.end_date
     *
     * @return the value of rgct_student_hist.end_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.end_date
     *
     * @param endDate the value for rgct_student_hist.end_date
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.operate
     *
     * @return the value of rgct_student_hist.operate
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.operate
     *
     * @param operate the value for rgct_student_hist.operate
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.id
     *
     * @return the value of rgct_student_hist.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.id
     *
     * @param id the value for rgct_student_hist.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.last_hist_id
     *
     * @return the value of rgct_student_hist.last_hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Long getLastHistId() {
        return lastHistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.last_hist_id
     *
     * @param lastHistId the value for rgct_student_hist.last_hist_id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setLastHistId(Long lastHistId) {
        this.lastHistId = lastHistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.name
     *
     * @return the value of rgct_student_hist.name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.name
     *
     * @param name the value for rgct_student_hist.name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.age
     *
     * @return the value of rgct_student_hist.age
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.age
     *
     * @param age the value for rgct_student_hist.age
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.class_name
     *
     * @return the value of rgct_student_hist.class_name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.class_name
     *
     * @param className the value for rgct_student_hist.class_name
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.current_state
     *
     * @return the value of rgct_student_hist.current_state
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Integer getCurrentState() {
        return currentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.current_state
     *
     * @param currentState the value for rgct_student_hist.current_state
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setCurrentState(Integer currentState) {
        this.currentState = currentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.is_lock
     *
     * @return the value of rgct_student_hist.is_lock
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.is_lock
     *
     * @param isLock the value for rgct_student_hist.is_lock
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.lock_scence
     *
     * @return the value of rgct_student_hist.lock_scence
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getLockScence() {
        return lockScence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.lock_scence
     *
     * @param lockScence the value for rgct_student_hist.lock_scence
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setLockScence(String lockScence) {
        this.lockScence = lockScence == null ? null : lockScence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_student_hist.nested_deep
     *
     * @return the value of rgct_student_hist.nested_deep
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Integer getNestedDeep() {
        return nestedDeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_student_hist.nested_deep
     *
     * @param nestedDeep the value for rgct_student_hist.nested_deep
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setNestedDeep(Integer nestedDeep) {
        this.nestedDeep = nestedDeep;
    }
}