package com.register.bean.dataObj;

public class RgctMethod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.id
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.module
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.interface_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.method_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.param
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.method_desc
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String methodDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.is_check_status
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String isCheckStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.is_check_del
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String isCheckDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rgct_method.is_back_hist
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    private String isBackHist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.id
     *
     * @return the value of rgct_method.id
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.id
     *
     * @param id the value for rgct_method.id
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.module
     *
     * @return the value of rgct_method.module
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.module
     *
     * @param module the value for rgct_method.module
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.interface_name
     *
     * @return the value of rgct_method.interface_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.interface_name
     *
     * @param interfaceName the value for rgct_method.interface_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.method_name
     *
     * @return the value of rgct_method.method_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.method_name
     *
     * @param methodName the value for rgct_method.method_name
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.param
     *
     * @return the value of rgct_method.param
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.param
     *
     * @param param the value for rgct_method.param
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.method_desc
     *
     * @return the value of rgct_method.method_desc
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getMethodDesc() {
        return methodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.method_desc
     *
     * @param methodDesc the value for rgct_method.method_desc
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc == null ? null : methodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.is_check_status
     *
     * @return the value of rgct_method.is_check_status
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getIsCheckStatus() {
        return isCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.is_check_status
     *
     * @param isCheckStatus the value for rgct_method.is_check_status
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setIsCheckStatus(String isCheckStatus) {
        this.isCheckStatus = isCheckStatus == null ? null : isCheckStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.is_check_del
     *
     * @return the value of rgct_method.is_check_del
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getIsCheckDel() {
        return isCheckDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.is_check_del
     *
     * @param isCheckDel the value for rgct_method.is_check_del
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setIsCheckDel(String isCheckDel) {
        this.isCheckDel = isCheckDel == null ? null : isCheckDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rgct_method.is_back_hist
     *
     * @return the value of rgct_method.is_back_hist
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public String getIsBackHist() {
        return isBackHist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rgct_method.is_back_hist
     *
     * @param isBackHist the value for rgct_method.is_back_hist
     *
     * @mbg.generated Tue Dec 31 17:48:43 CST 2019
     */
    public void setIsBackHist(String isBackHist) {
        this.isBackHist = isBackHist == null ? null : isBackHist.trim();
    }
}