package com.register.bean.dataObj;

public class StatusDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statusdictionary.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statusdictionary.status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statusdictionary.statusDisc
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    private String statusdisc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusdictionary.id
     *
     * @return the value of statusdictionary.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusdictionary.id
     *
     * @param id the value for statusdictionary.id
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusdictionary.status
     *
     * @return the value of statusdictionary.status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusdictionary.status
     *
     * @param status the value for statusdictionary.status
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusdictionary.statusDisc
     *
     * @return the value of statusdictionary.statusDisc
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public String getStatusdisc() {
        return statusdisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusdictionary.statusDisc
     *
     * @param statusdisc the value for statusdictionary.statusDisc
     *
     * @mbg.generated Mon Dec 02 20:59:53 CST 2019
     */
    public void setStatusdisc(String statusdisc) {
        this.statusdisc = statusdisc == null ? null : statusdisc.trim();
    }
}