package com.register.bean.dataObj;

public class StatusDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.before_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private String beforeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.run_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private String runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.event_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.after_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private String afterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.listeners_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private Integer listenersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.callback_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    private Integer callbackId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.id
     *
     * @return the value of status.id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.id
     *
     * @param id the value for status.id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.before_status
     *
     * @return the value of status.before_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public String getBeforeStatus() {
        return beforeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.before_status
     *
     * @param beforeStatus the value for status.before_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setBeforeStatus(String beforeStatus) {
        this.beforeStatus = beforeStatus == null ? null : beforeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.run_status
     *
     * @return the value of status.run_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public String getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.run_status
     *
     * @param runStatus the value for status.run_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setRunStatus(String runStatus) {
        this.runStatus = runStatus == null ? null : runStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.event_id
     *
     * @return the value of status.event_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.event_id
     *
     * @param eventId the value for status.event_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.after_status
     *
     * @return the value of status.after_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public String getAfterStatus() {
        return afterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.after_status
     *
     * @param afterStatus the value for status.after_status
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setAfterStatus(String afterStatus) {
        this.afterStatus = afterStatus == null ? null : afterStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.listeners_id
     *
     * @return the value of status.listeners_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public Integer getListenersId() {
        return listenersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.listeners_id
     *
     * @param listenersId the value for status.listeners_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setListenersId(Integer listenersId) {
        this.listenersId = listenersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.callback_id
     *
     * @return the value of status.callback_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public Integer getCallbackId() {
        return callbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.callback_id
     *
     * @param callbackId the value for status.callback_id
     *
     * @mbg.generated Mon Dec 02 20:56:15 CST 2019
     */
    public void setCallbackId(Integer callbackId) {
        this.callbackId = callbackId;
    }
}