package com.core.rule.bean.dataObj;

public class PropertyDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.id
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.draftNo
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    private String draftno;

    public PropertyDo(){}
    public PropertyDo(String draftno, String property) {
        this.property = property;
        this.draftno = draftno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.id
     *
     * @return the value of property.id
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.id
     *
     * @param id the value for property.id
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property
     *
     * @return the value of property.property
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property
     *
     * @param property the value for property.property
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.draftNo
     *
     * @return the value of property.draftNo
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public String getDraftno() {
        return draftno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.draftNo
     *
     * @param draftno the value for property.draftNo
     *
     * @mbg.generated Fri Nov 15 15:08:28 CST 2019
     */
    public void setDraftno(String draftno) {
        this.draftno = draftno == null ? null : draftno.trim();
    }
}