package com.core.rule.bean.dataObj;

public class RuleDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.id
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.draftNo
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private String draftno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.property
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.isRegex
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private Integer isregex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.isJsEngine
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private Integer isjsengine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.isEmpty
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private Integer isempty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.length
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.type
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    private String type;


    public RuleDo(){}
    public RuleDo(String draftno, String property, Integer isregex, Integer isjsengine, Integer isempty, Integer length, String type) {
        this.draftno = draftno;
        this.property = property;
        this.isregex = isregex;
        this.isjsengine = isjsengine;
        this.isempty = isempty;
        this.length = length;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.id
     *
     * @return the value of rule.id
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */



    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.id
     *
     * @param id the value for rule.id
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.draftNo
     *
     * @return the value of rule.draftNo
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public String getDraftno() {
        return draftno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.draftNo
     *
     * @param draftno the value for rule.draftNo
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setDraftno(String draftno) {
        this.draftno = draftno == null ? null : draftno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.property
     *
     * @return the value of rule.property
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.property
     *
     * @param property the value for rule.property
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.isRegex
     *
     * @return the value of rule.isRegex
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public Integer getIsregex() {
        return isregex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.isRegex
     *
     * @param isregex the value for rule.isRegex
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setIsregex(Integer isregex) {
        this.isregex = isregex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.isJsEngine
     *
     * @return the value of rule.isJsEngine
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public Integer getIsjsengine() {
        return isjsengine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.isJsEngine
     *
     * @param isjsengine the value for rule.isJsEngine
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setIsjsengine(Integer isjsengine) {
        this.isjsengine = isjsengine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.isEmpty
     *
     * @return the value of rule.isEmpty
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public Integer getIsempty() {
        return isempty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.isEmpty
     *
     * @param isempty the value for rule.isEmpty
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setIsempty(Integer isempty) {
        this.isempty = isempty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.length
     *
     * @return the value of rule.length
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.length
     *
     * @param length the value for rule.length
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.type
     *
     * @return the value of rule.type
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.type
     *
     * @param type the value for rule.type
     *
     * @mbg.generated Thu Nov 21 16:34:50 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}